// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:8080' | (string & {});
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type LoginInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    handle_or_email: string;
    password: string;
};

export type SelfUser = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    admin: boolean;
    created_at: string;
    display_name: string;
    email: string;
    handle: string;
    id: string;
    verified: boolean;
};

export type SessionDto = {
    created_at: string;
    current: boolean;
    id: string;
    ip: string;
    last_seen: string;
    user_agent: string;
};

export type SignupInBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * optional; defaults to the handle
     */
    display_name?: string;
    email: string;
    /**
     * lowercase letters, digits and underscore
     */
    handle: string;
    /**
     * 72 is bcrypt's limit
     */
    password: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type LoginInBodyWritable = {
    handle_or_email: string;
    password: string;
};

export type SelfUserWritable = {
    admin: boolean;
    created_at: string;
    display_name: string;
    email: string;
    handle: string;
    id: string;
    verified: boolean;
};

export type SignupInBodyWritable = {
    /**
     * optional; defaults to the handle
     */
    display_name?: string;
    email: string;
    /**
     * lowercase letters, digits and underscore
     */
    handle: string;
    /**
     * 72 is bcrypt's limit
     */
    password: string;
};

export type LoginData = {
    body: LoginInBodyWritable;
    headers?: {
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/login';
};

export type LoginErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * OK
     */
    200: SelfUser;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout';
};

export type LogoutErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type LogoutAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/logout-all';
};

export type LogoutAllErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type LogoutAllError = LogoutAllErrors[keyof LogoutAllErrors];

export type LogoutAllResponses = {
    /**
     * No Content
     */
    204: void;
};

export type LogoutAllResponse = LogoutAllResponses[keyof LogoutAllResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type MeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    /**
     * OK
     */
    200: SelfUser;
};

export type MeResponse = MeResponses[keyof MeResponses];

export type ListSessionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/sessions';
};

export type ListSessionsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListSessionsError = ListSessionsErrors[keyof ListSessionsErrors];

export type ListSessionsResponses = {
    /**
     * OK
     */
    200: Array<SessionDto> | null;
};

export type ListSessionsResponse = ListSessionsResponses[keyof ListSessionsResponses];

export type RevokeSessionData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/sessions/{id}';
};

export type RevokeSessionErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RevokeSessionError = RevokeSessionErrors[keyof RevokeSessionErrors];

export type RevokeSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RevokeSessionResponse = RevokeSessionResponses[keyof RevokeSessionResponses];

export type SignupData = {
    body: SignupInBodyWritable;
    headers?: {
        'User-Agent'?: string;
    };
    path?: never;
    query?: never;
    url: '/api/signup';
};

export type SignupErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * Created
     */
    201: SelfUser;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];
